// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgfBGrEj0CzfG5zYs0KcE1-pkzcdlrorg',
    appId: '1:446434901424:web:6b020a039dd208eae8ea75',
    messagingSenderId: '446434901424',
    projectId: 'yahya200801-cf244',
    authDomain: 'yahya200801-cf244.firebaseapp.com',
    storageBucket: 'yahya200801-cf244.firebasestorage.app',
    measurementId: 'G-1H2QXSYXSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi62-YBMYWx_FCNqi-EN8UFz3kYmB44tA',
    appId: '1:446434901424:android:f5b8cfbb41ad96b8e8ea75',
    messagingSenderId: '446434901424',
    projectId: 'yahya200801-cf244',
    storageBucket: 'yahya200801-cf244.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdlKumctbkmOy2Zb10wCndko2Hxs3-NDA',
    appId: '1:446434901424:ios:55b7573f584a3167e8ea75',
    messagingSenderId: '446434901424',
    projectId: 'yahya200801-cf244',
    storageBucket: 'yahya200801-cf244.firebasestorage.app',
    iosBundleId: 'com.example.jessichoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdlKumctbkmOy2Zb10wCndko2Hxs3-NDA',
    appId: '1:446434901424:ios:55b7573f584a3167e8ea75',
    messagingSenderId: '446434901424',
    projectId: 'yahya200801-cf244',
    storageBucket: 'yahya200801-cf244.firebasestorage.app',
    iosBundleId: 'com.example.jessichoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgfBGrEj0CzfG5zYs0KcE1-pkzcdlrorg',
    appId: '1:446434901424:web:529d19c6985b1f2fe8ea75',
    messagingSenderId: '446434901424',
    projectId: 'yahya200801-cf244',
    authDomain: 'yahya200801-cf244.firebaseapp.com',
    storageBucket: 'yahya200801-cf244.firebasestorage.app',
    measurementId: 'G-60S0K75BQD',
  );
}
