// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoG7N-8AglmozoOD9UFx7CWWpJyY8s-8Y',
    appId: '1:854015954290:web:82bf21b71363f9f4b3e1eb',
    messagingSenderId: '854015954290',
    projectId: 'fizz-me',
    authDomain: 'fizz-me.firebaseapp.com',
    storageBucket: 'fizz-me.firebasestorage.app',
    measurementId: 'G-ETNW1B769X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcVonAXRxtNcShQglMuGGbfnJxWophnJ0',
    appId: '1:854015954290:android:53d797a217581453b3e1eb',
    messagingSenderId: '854015954290',
    projectId: 'fizz-me',
    storageBucket: 'fizz-me.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxtbcy8AGJ6moKJTmaR_p_Z2H4a_VrH10',
    appId: '1:854015954290:ios:e4b36d9c5d32d329b3e1eb',
    messagingSenderId: '854015954290',
    projectId: 'fizz-me',
    storageBucket: 'fizz-me.firebasestorage.app',
    androidClientId: '854015954290-k5pgfbd7jlqmeh43mbo78gke5h9v0tr4.apps.googleusercontent.com',
    iosClientId: '854015954290-l092rqt7b679jnd9vll6s2ncc1sov4ll.apps.googleusercontent.com',
    iosBundleId: 'com.example.guvena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxtbcy8AGJ6moKJTmaR_p_Z2H4a_VrH10',
    appId: '1:854015954290:ios:e4b36d9c5d32d329b3e1eb',
    messagingSenderId: '854015954290',
    projectId: 'fizz-me',
    storageBucket: 'fizz-me.firebasestorage.app',
    androidClientId: '854015954290-k5pgfbd7jlqmeh43mbo78gke5h9v0tr4.apps.googleusercontent.com',
    iosClientId: '854015954290-l092rqt7b679jnd9vll6s2ncc1sov4ll.apps.googleusercontent.com',
    iosBundleId: 'com.example.guvena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoG7N-8AglmozoOD9UFx7CWWpJyY8s-8Y',
    appId: '1:854015954290:web:589fb3d7c3b8526bb3e1eb',
    messagingSenderId: '854015954290',
    projectId: 'fizz-me',
    authDomain: 'fizz-me.firebaseapp.com',
    storageBucket: 'fizz-me.firebasestorage.app',
    measurementId: 'G-MQMWTJ2YC1',
  );

}