import 'package:get/get.dart';

class LocalLocalizations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'app_name': 'Jessichoo',
      'welcome': 'Welcome to Jessichoo',
      'login': 'Login',
      'signup': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'home': 'Home',
      'profile': 'Profile',
      'switch_to': 'Switch to',
      'language': 'Language',
      'notification': 'Notification',
      'log_out': 'Log out',
      'edit_profile': 'Edit Profile',
      'specials': 'Specials',
      'reviews': 'Reviews',
      'my_meetups': 'My Meetups',
      'joined_meetups': 'Joined Meetups',
      'meetup_cover': 'Meetup Cover',
      'meetup_name': 'Meetup Name',
      'meetup_topic': 'Meetup Topic',
      'price': 'Price',
      'location': 'Location',
      'area': 'Area',
      'time': 'Time',
      'date': 'Date',
      'meetup_description': 'Meetup Description',
      'post_meetup': 'Post Meetup',
      'chef': 'Chef',
      'chef_booking': 'Chef Booking',
      'ongoing_meetups_in_your_area': 'Ongoing Meetups in Your Area',
      'search': 'Search',
      'select': 'Select',
      'your_message': 'Your Message',
      'italy': 'Italy',
      'france': 'France',
      'germany': 'Germany',
      'spain': 'Spain',
      'japan': 'Japan',
      'welcome_to_app': 'Welcome to the app',
      'registration': 'Registration',
      'reset': 'Reset',
      'back': 'Back',
      'confirm_password': 'Confirm Password',
      'welcome_to_chefconnect':
          'Welcome to ChefConnect! Your culinary adventure starts here. Log in to explore amazing chefs and find the perfect match for your kitchen!',
      'verify': 'Verify',
      'otp_verification': 'OTP verification',
      'otp_message': 'OTP is a one-time password so we can know it\'s you.',
      'didnt_get_otp': 'Didn\'t get the OTP?',
      'resend': 'Resend',
      'how_will_you_use_this_app': 'How will you use this app mostly?',
      'as_chef': 'As Chef',
      'as_user': 'As User',
      'continue': 'Continue',
      'this_can_always_be_changed':
          'This can always be changed in the settings',
      'starting_from': 'Starting from',
      'bio': 'Bio',
      'rating': 'Rating',
      'book_now': 'Book Now',
      'organizer_review': 'Organizer Review',
      'topic': 'Topic',
      'join_now': 'Join Now',
      'review_meetup': 'Review Meetup',
      'sent_otp_to': 'Sent an OTP to',
      'set_up_new_password': 'Set up your new password',
      'dont_share_password': 'Don\'t share your password with anyone',
      'save': 'Save',

      "make_an_offer": "Make an Offer",
      "offer_rejected_refund":
          "If the offer gets rejected\nyour money will be refunded",
      "proceed_to_pay": "Proceed to Pay",
      "submit": "Submit",
      "please_fill_all_fields": "Please fill all fields",
      "error": "Error",
    },
    'es_ES': {
      'app_name': 'Jessichoo',
      'welcome': 'Bienvenido a Jessichoo',
      'login': 'Iniciar sesión',
      'signup': 'Registrarse',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'forgot_password': '¿Olvidaste tu contraseña?',
      'home': 'Inicio',
      'profile': 'Perfil',
      'switch_to': 'Cambiar a',
      'language': 'Idioma',
      'notification': 'Notificación',
      'log_out': 'Cerrar sesión',
      'edit_profile': 'Editar perfil',
      'specials': 'Especiales',
      'reviews': 'Reseñas',
      'my_meetups': 'Mis Encuentros',
      'joined_meetups': 'Encuentros Unidos',
      'meetup_cover': 'Portada del Encuentro',
      'meetup_name': 'Nombre del Encuentro',
      'meetup_topic': 'Tema del Encuentro',
      'price': 'Precio',
      'location': 'Ubicación',
      'area': 'Área',
      'time': 'Hora',
      'date': 'Fecha',
      'meetup_description': 'Descripción del Encuentro',
      'post_meetup': 'Publicar Encuentro',
      'chef': 'Chef',
      'chef_booking': 'Reserva del Chef',
      'ongoing_meetups_in_your_area': 'Encuentros en curso en tu área',
      'search': 'Buscar',
      'select': 'Seleccionar',
      'your_message': 'Tu Mensaje',
      'italy': 'Italia',
      'france': 'Francia',
      'germany': 'Alemania',
      'spain': 'España',
      'japan': 'Japón',
      'welcome_to_app': 'Bienvenido a la aplicación',
      'registration': 'Registro',
      'reset': 'Restablecer',
      'back': 'Atrás',
      'confirm_password': 'Confirmar Contraseña',
      'welcome_to_chefconnect':
          '¡Bienvenido a ChefConnect! Tu aventura culinaria comienza aquí. Inicia sesión para explorar chefs increíbles y encontrar el compañero perfecto para tu cocina.',
      'verify': 'Verificar',
      'otp_verification': 'Verificación de OTP',
      'otp_message':
          'El OTP es una contraseña de un solo uso para que podamos saber que eres tú.',
      'didnt_get_otp': '¿No recibiste el OTP?',
      'resend': 'Reenviar',
      'how_will_you_use_this_app':
          '¿Cómo usarás esta aplicación principalmente?',
      'as_chef': 'Como Chef',
      'as_user': 'Como Usuario',
      'continue': 'Continuar',
      'this_can_always_be_changed':
          'Esto siempre se puede cambiar en la configuración',
      'starting_from': 'Empezando desde',

      // New terms in Spanish
      'bio': 'Biografía',
      'rating': 'Valoración',
      'book_now': 'Reservar Ahora',
      'organizer_review': 'Reseña del Organizador',
      'topic': 'Tema',
      'join_now': 'Unirse Ahora',
      'review_meetup': 'Revisar Encuentro', // Spanish
      'sent_otp_to': 'Se envió un OTP a',
      'set_up_new_password': 'Configura tu nueva contraseña',
      'dont_share_password': 'No compartas tu contraseña con nadie',
      'save': 'Guardar',
      "make_an_offer": "Haz una oferta",
      "offer_rejected_refund":
          "Si la oferta es rechazada\nse te reembolsará el dinero",
      "proceed_to_pay": "Proceder al pago",
      "submit": "Enviar",
      "please_fill_all_fields": "Por favor completa todos los campos",
      "error": "Error",
    },
    'de_DE': {
      'app_name': 'Jessichoo',
      'welcome': 'Willkommen bei Jessichoo',
      'login': 'Einloggen',
      'signup': 'Anmelden',
      'email': 'E-Mail',
      'password': 'Passwort',
      'forgot_password': 'Passwort vergessen?',
      'home': 'Zuhause',
      'profile': 'Profil',
      'switch_to': 'Wechseln zu',
      'language': 'Sprache',
      'notification': 'Benachrichtigung',
      'log_out': 'Abmelden',
      'edit_profile': 'Profil bearbeiten',
      'specials': 'Spezialitäten',
      'reviews': 'Bewertungen',
      'my_meetups': 'Meine Treffen',
      'joined_meetups': 'Beigetretene Treffen',
      'meetup_cover': 'Treffen Titelbild',
      'meetup_name': 'Treffen Name',
      'meetup_topic': 'Treffen Thema',
      'price': 'Preis',
      'location': 'Ort',
      'area': 'Bereich',
      'time': 'Uhrzeit',
      'date': 'Datum',
      'meetup_description': 'Treffen Beschreibung',
      'post_meetup': 'Treffen posten',
      'chef': 'Koch',
      'chef_booking': 'Kochbuchung',
      'ongoing_meetups_in_your_area': 'Laufende Treffen in Ihrer Nähe',
      'search': 'Suche',
      'select': 'Auswählen',
      'your_message': 'Ihre Nachricht',
      'italy': 'Italien',
      'france': 'Frankreich',
      'germany': 'Deutschland',
      'spain': 'Spanien',
      'japan': 'Japan',
      'welcome_to_app': 'Willkommen in der App',
      'registration': 'Registrierung',
      'reset': 'Zurücksetzen',
      'back': 'Zurück',
      'confirm_password': 'Passwort bestätigen',
      'welcome_to_chefconnect':
          'Willkommen bei ChefConnect! Dein kulinarisches Abenteuer beginnt hier. Melde dich an, um erstaunliche Köche zu entdecken und den perfekten Partner für deine Küche zu finden!',
      'verify': 'Verifizieren',
      'otp_verification': 'OTP-Verifizierung',
      'otp_message':
          'OTP ist ein einmaliges Passwort, damit wir wissen, dass du es bist.',
      'didnt_get_otp': 'Hast du das OTP nicht erhalten?',
      'resend': 'Erneut senden',
      'how_will_you_use_this_app':
          'Wie wirst du diese App hauptsächlich nutzen?',
      'as_chef': 'Als Koch',
      'as_user': 'Als Benutzer',
      'continue': 'Fortfahren',
      'this_can_always_be_changed':
          'Dies kann immer in den Einstellungen geändert werden',
      'starting_from': 'Ab',
      'bio': 'Biografie',
      'rating': 'Bewertung',
      'book_now': 'Jetzt buchen',
      'organizer_review': 'Bewertung des Organisators',
      'topic': 'Thema',
      'join_now': 'Jetzt beitreten',
      'review_meetup': 'Treffen Bewerten',
      'sent_otp_to': 'OTP an gesendet an',
      'set_up_new_password': 'Richte dein neues Passwort ein',
      'dont_share_password': 'Teile dein Passwort mit niemandem',
      'save': 'Speichern',
      "make_an_offer": "Mach ein Angebot",
      "offer_rejected_refund":
          "Wenn das Angebot abgelehnt wird,\nwird dein Geld zurückerstattet",
      "proceed_to_pay": "Zur Bezahlung fortfahren",
      "submit": "Einreichen",
      "please_fill_all_fields": "Bitte fülle alle Felder aus",
      "error": "Fehler",
    },
  };
}
